sudo: required
services:
  - docker

before_install:
  - docker build -t dariusmunteanu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dariusmunteanu/docker-react npm run test

language: generic 